name: shared_core
description: Shared models, services, and themes for Espy Project.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.11.0
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.5.1
  firebase_database: ^12.4.1
  firebase_storage: ^13.4.1
  cloud_functions: ^6.3.1
  provider: ^6.1.2
  google_fonts: ^8.1.0
  intl: 0.20.2
  shared_preferences: ^2.5.5
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.2
  pay: ^3.3.0
  pdf: ^3.11.1
  printing: ^5.13.3
  lucide_icons_flutter: ^3.1.14+2
  geoflutterfire_plus: ^0.0.34
  rxdart: ^0.28.0

dependency_overrides: {}
